services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:3000"
      REDIS_URL: "redis://redis:6379"
    env_file:
      - db.env
      - docmost.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /mnt/dockerdata/docmost/app:/app/data/storage
    networks:
      - docmost

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
    env_file:
      - db.env
    restart: unless-stopped
    volumes:
      - /mnt/dockerdata/docmost/postgres_db:/var/lib/postgresql/data
    networks:
      - docmost

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - /mnt/dockerdata/docmost/redis_data:/data
    networks:
      - docmost

networks:
  docmost:
