version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - zipline.env
    volumes:
      - /mnt/docker_data/zipline/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zipline

  zipline:
    image: ghcr.io/diced/zipline
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - zipline.env
    volumes:
      - /mnt/docker_data/zipline/uploads:/zipline/uploads
      - /mnt/docker_data/zipline/public:/zipline/public
    networks:
      - zipline
    depends_on:
      - 'postgres'

volumes:
  pg_data:
networks:
  zipline:
