name: Testing

on: workflow_dispatch

jobs:
  main:
    name: nfiwjeof
    runs-on: [self-hosted]
  
    steps:
    - name: ehofehofi
      run: |
        python3 -c 'import os; print('{"hello":"something"}')'
