name: Testing

on: workflow_dispatch

jobs:
  main:
    name: nfiwjeof
    runs-on: [self-hosted]
  
    steps:
    - name: Get Information
      id: get-data
      run: |
        python3 /tmp/main.py >> ${GITHUB_OUTPUT}
    
    - name: Display Information
      run: | 
        echo '${{ steps.get-data.outputs.data }}' | jq -r .file
