name: Testing

on: workflow_dispatch

jobs:
  main:
    name: nfiwjeof
    runs-on: [self-hosted]
  
    steps:
    - name: Get Information
      id: get-data
      run: |
        python3 /tmp/main.py >> ${GITHUB_OUTPUT}
    
    - name: Load Information
      run: | 
        python3 -c '''import json; j=json.loads("""
        ${{ steps.get-data.outputs.data }}"""); print(j.get("name"))'''

